namespace dotnet_error_lookup.Data.Errors;

public class CS0204 : IErrorOrWarning
{
    SyntaxErrorType IErrorOrWarning.ErrorType => SyntaxErrorType.Error;
    string IErrorOrWarning.Name => @"CS0204";
    string IErrorOrWarning.Message => @"Only 65534 locals, including those generated by the compiler, are allowed";
    string IErrorOrWarning.Explanation => @"[original] Only 65534 locals, including those generated by the compiler, are allowed";
    string IErrorOrWarning.SampleCode => string.Empty;
    string IErrorOrWarning.SampleFix => string.Empty;
    string IErrorOrWarning.DocumentationReference => @"https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0204";
}
